### ISSUE TITLE
compiled output gets truncated at 152 chars

### ISSUE THREAD

**Issue by Munter** [Munter/fusile#1]
When I use [buf.write](http://nodejs.org/api/buffer.html#buffer_buf_write_string_offset_length_encoding) it seems that the compiled result is correctly written to the SlowBuffer I get passed as an argument.

When I [log both the contents of the buffer and the length](https://github.com/Munter/fusile/blob/master/lib/index.js#L189-L194) that I just wrote to the buffer, I correctly get the compiled content and the amount of chars of the compiled content.

But when i `cat path/to/file` and it is a compiled output, the result in my terminal gets truncated to around 152 chars.

This can be reproduced in the terminal, but also clearly shows when running the unit tests.

@mafintosh do you have any idea what I could be doing wrong?

**Comment by mafintosh** [comment]
You probably want to use `.copy` instead of `.write` since you are deadling with buffers, http://nodejs.org/api/buffer.html#buffer_buf_copy_targetbuffer_targetstart_sourcestart_sourceend

How big to you report the file to be in your stat call? https://github.com/Munter/fusile/blob/master/lib/index.js#L134-L141

**Comment by Munter** [comment]
Ah, of course it's the stat call. I'm reporting the file to be as big as the source file, which is obviously not the case when it is being transformed. I wonder how I can deal with that without compiling everything on stat, creating some very slow stat calls

**Comment by Munter** [comment]
Bummer. That didn't fix it. Sometimes it works, but most times I get a bunch of null bytes out in the end, corresponding to the length diff between the actual content and my fake stat size.

**Comment by mafintosh** [comment]
couldn't you just calculate the length when statting and cache the file result? (in most cases statting only happens before a read anyways)

**Comment by Munter** [comment]
I could certainly move the compiler step to the stat call. Looking at the logs I was under the impression that stats were much more common though

**Comment by Munter** [comment]
This is what I'm getting when I log stats, reads and opens for file types that are potentially covered by precompilers when I run a test that only touches the `less/basic.less` file:

```
$ mocha -g less


  In a mounted filesystem
File system started at test/READ
To stop it, type this in another shell: fusermount -u test/READ
stat /6to5/basic.js
stat /less/_import.less
stat /less/basic.less
stat /less/external.less
stat /markdown/basic.md
stat /markdown/opts.md
stat /minify-js/basic.js
stat /minify-js/opts.js
stat /scss/_mixin_lib.scss
stat /scss/basic.scss
stat /scss/external.scss
    when reading uncompiled files
open /home/munter/git/fusile/test/fixtures/source/less/basic.less
read /home/munter/git/fusile/test/fixtures/source/less/basic.less 0 4096
Adapter found: less
Cache miss, compiling: /home/munter/git/fusile/test/fixtures/source/less/basic.less
      1) should compile less/basic.less
```

That's a lot of stats on other files that seem completely unrelated, which would cause a massive slowdown if I had to compile those as well

**Comment by mafintosh** [comment]
Hmm. Still is it bad to just compile+cache on every stat call? You probably only need to cache invalidate when writes happen (and you can track that as well)

**Comment by Munter** [comment]
I guess it would just take a long tie for the file system to unblock in larger environments when first mounting it. For now I'm controlling cache by just keeping the mtime and fire a stat against the original file before deciding whether to serve the cached version or recompile. Eventually I can listen to writes on the source directory to trigger cache invalidations.

I'll see how compiling on stat works out
